### ISSUE TITLE
PATCH /folders/:id/relationships/children fails with meta.relation.position present

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#1524]
### Expected behavior

Patching folder's children with position set should be replace all children using the position passed.

```http
PATCH /folders/12/relationships/children

{
    "data": [
    	{
	        "id": "6",
	        "type": "documents",
	        "meta": {
	        	"relation": {
	        		"position": 2
	        	}
	        }
    	},
    	{
	        "id": "5",
	        "type": "documents",
	        "meta": {
	        	"relation": {
	        		"position": 1
	        	}
	        }
    	}
    ]
}
```

### Actual behavior

A `400 Bad Request` happens with error

```json
{
    "error": {
        "status": "400",
        "title": "Error linking entities",
        "detail": "[object_id.isPositionUnique]: Folders cannot be made ubiquitous, other objects cannot appear twice in the same folder",
        "meta": {
            "trace": [
                "#0 /home/bato/ws/github/bedita/bedita4/plugins/BEdita/Core/src/Model/Action/UpdateAssociatedAction.php(143): BEdita\\Core\\Model\\Action\\SetAssociatedAction->update(Object(BEdita\\Core\\Model\\Entity\\Folder), Array)",
                "#1 /home/bato/ws/github/bedita/bedita4/plugins/BEdita/Core/src/Model/Action/SetRelatedObjectsAction.php(95): BEdita\\Core\\Model\\Action\\UpdateAssociatedAction->execute(Array)",
                "#2 /home/bato/ws/github/bedita/bedita4/plugins/BEdita/Core/src/Model/Action/UpdateAssociatedAction.php(143): BEdita\\Core\\Model\\Action\\SetRelatedObjectsAction->update(Object(BEdita\\Core\\Model\\Entity\\Folder), Array)",
                "#3 /home/bato/ws/github/bedita/bedita4/plugins/BEdita/Core/src/Model/Action/UpdateRelatedObjectsAction.php(67): BEdita\\Core\\Model\\Action\\UpdateAssociatedAction->execute(Array)",
                "#4 /home/bato/ws/github/bedita/bedita4/plugins/BEdita/API/src/Model/Action/UpdateAssociatedAction.php(80): BEdita\\Core\\Model\\Action\\UpdateRelatedObjectsAction->execute(Array)",
                "#5 /home/bato/ws/github/bedita/bedita4/plugins/BEdita/Core/src/Model/Action/BaseAction.php(73): BEdita\\API\\Model\\Action\\UpdateAssociatedAction->execute(Array)",
                "#6 /home/bato/ws/github/bedita/bedita4/plugins/BEdita/API/src/Controller/ObjectsController.php(351): BEdita\\Core\\Model\\Action\\BaseAction->__invoke(Array)",
                "#7 /home/bato/ws/github/bedita/bedita4/vendor/cakephp/cakephp/src/Controller/Controller.php(440): BEdita\\API\\Controller\\ObjectsController->relationships()",
                "#8 /home/bato/ws/github/bedita/bedita4/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(119): Cake\\Controller\\Controller->invokeAction()",
                "#9 /home/bato/ws/github/bedita/bedita4/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(93): Cake\\Http\\ActionDispatcher->_invoke(Object(BEdita\\API\\Controller\\FoldersController))",
                "#10 /home/bato/ws/github/bedita/bedita4/vendor/cakephp/cakephp/src/Http/BaseApplication.php(109): Cake\\Http\\ActionDispatcher->dispatch(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response))",
                "#11 /home/bato/ws/github/bedita/bedita4/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\\Http\\BaseApplication->__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response), Object(Cake\\Http\\Runner))",
                "#12 /home/bato/ws/github/bedita/bedita4/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(104): Cake\\Http\\Runner->__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response))",
                "#13 /home/bato/ws/github/bedita/bedita4/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\\Routing\\Middleware\\RoutingMiddleware->__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response), Object(Cake\\Http\\Runner))",
                "#14 /home/bato/ws/github/bedita/bedita4/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\\Http\\Runner->__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response))",
                "#15 /home/bato/ws/github/bedita/bedita4/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\\Routing\\Middleware\\AssetMiddleware->__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response), Object(Cake\\Http\\Runner))",
                "#16 /home/bato/ws/github/bedita/bedita4/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\\Http\\Runner->__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response))",
                "#17 /home/bato/ws/github/bedita/bedita4/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\\Error\\Middleware\\ErrorHandlerMiddleware->__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response), Object(Cake\\Http\\Runner))",
                "#18 /home/bato/ws/github/bedita/bedita4/plugins/BEdita/API/src/Middleware/CorsMiddleware.php(94): Cake\\Http\\Runner->__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response))",
                "#19 /home/bato/ws/github/bedita/bedita4/vendor/cakephp/cakephp/src/Http/Runner.php(65): BEdita\\API\\Middleware\\CorsMiddleware->__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response), Object(Cake\\Http\\Runner))",
                "#20 /home/bato/ws/github/bedita/bedita4/plugins/BEdita/API/src/Middleware/AnalyticsMiddleware.php(134): Cake\\Http\\Runner->__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response))",
                "#21 /home/bato/ws/github/bedita/bedita4/vendor/cakephp/cakephp/src/Http/Runner.php(65): BEdita\\API\\Middleware\\AnalyticsMiddleware->__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response), Object(Cake\\Http\\Runner))",
                "#22 /home/bato/ws/github/bedita/bedita4/vendor/bedita/dev-tools/src/Middleware/HtmlMiddleware.php(43): Cake\\Http\\Runner->__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response))",
                "#23 /home/bato/ws/github/bedita/bedita4/vendor/cakephp/cakephp/src/Http/Runner.php(65): BEdita\\DevTools\\Middleware\\HtmlMiddleware->__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response), Object(Cake\\Http\\Runner))",
                "#24 /home/bato/ws/github/bedita/bedita4/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php(52): Cake\\Http\\Runner->__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response))",
                "#25 /home/bato/ws/github/bedita/bedita4/vendor/cakephp/cakephp/src/Http/Runner.php(65): DebugKit\\Middleware\\DebugKitMiddleware->__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response), Object(Cake\\Http\\Runner))",
                "#26 /home/bato/ws/github/bedita/bedita4/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\\Http\\Runner->__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response))",
                "#27 /home/bato/ws/github/bedita/bedita4/vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\\Http\\Runner->run(Object(Cake\\Http\\MiddlewareQueue), Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response))",
                "#28 /home/bato/ws/github/bedita/bedita4/webroot/index.php(40): Cake\\Http\\Server->run()",
                "#29 {main}"
            ]
        }
    },
    "links": {
        "self": "http://bedita4.localhost/folders/3/relationships/children",
        "home": "http://bedita4.localhost/home"
    }
}
```

### Note

The same patch without `meta` works well.

**Comment by batopa** [comment]
To verify after https://github.com/bedita/bedita/issues/1531

**Comment by batopa** [comment]
Trying now... we have a new error!

```json
{
    "error": {
        "status": "500",
        "title": "Call to a member function getErrors() on array",
        "meta": {
            "trace": [
                "#0 \/home\/bato\/ws\/github\/bedita\/bedita4\/plugins\/BEdita\/Core\/src\/Model\/Action\/UpdateAssociatedAction.php(50): BEdita\\Core\\Model\\Action\\SetAssociatedAction-\u003Eupdate(Object(BEdita\\Core\\Model\\Entity\\Folder), Array)",
                "#1 \/home\/bato\/ws\/github\/bedita\/bedita4\/plugins\/BEdita\/Core\/src\/Model\/Action\/SetRelatedObjectsAction.php(38): BEdita\\Core\\Model\\Action\\UpdateAssociatedAction-\u003Eexecute(Array)",
                "#2 \/home\/bato\/ws\/github\/bedita\/bedita4\/plugins\/BEdita\/Core\/src\/Model\/Action\/UpdateAssociatedAction.php(50): BEdita\\Core\\Model\\Action\\SetRelatedObjectsAction-\u003Eupdate(Object(BEdita\\Core\\Model\\Entity\\Folder), Array)",
                "#3 \/home\/bato\/ws\/github\/bedita\/bedita4\/plugins\/BEdita\/Core\/src\/Model\/Action\/UpdateRelatedObjectsAction.php(35): BEdita\\Core\\Model\\Action\\UpdateAssociatedAction-\u003Eexecute(Array)",
                "#4 \/home\/bato\/ws\/github\/bedita\/bedita4\/plugins\/BEdita\/API\/src\/Model\/Action\/UpdateAssociatedAction.php(81): BEdita\\Core\\Model\\Action\\UpdateRelatedObjectsAction-\u003Eexecute(Array)",
                "#5 \/home\/bato\/ws\/github\/bedita\/bedita4\/plugins\/BEdita\/Core\/src\/Model\/Action\/BaseAction.php(72): BEdita\\API\\Model\\Action\\UpdateAssociatedAction-\u003Eexecute(Array)",
                "#6 \/home\/bato\/ws\/github\/bedita\/bedita4\/plugins\/BEdita\/API\/src\/Controller\/ObjectsController.php(357): BEdita\\Core\\Model\\Action\\BaseAction-\u003E__invoke(Array)",
                "#7 \/home\/bato\/ws\/github\/bedita\/bedita4\/plugins\/BEdita\/API\/src\/Controller\/FoldersController.php(112): BEdita\\API\\Controller\\ObjectsController-\u003Erelationships()",
                "#8 \/home\/bato\/ws\/github\/bedita\/bedita4\/vendor\/cakephp\/cakephp\/src\/Controller\/Controller.php(609): BEdita\\API\\Controller\\FoldersController-\u003Erelationships()",
                "#9 \/home\/bato\/ws\/github\/bedita\/bedita4\/vendor\/cakephp\/cakephp\/src\/Http\/ActionDispatcher.php(120): Cake\\Controller\\Controller-\u003EinvokeAction()",
                "#10 \/home\/bato\/ws\/github\/bedita\/bedita4\/vendor\/cakephp\/cakephp\/src\/Http\/ActionDispatcher.php(94): Cake\\Http\\ActionDispatcher-\u003E_invoke(Object(BEdita\\API\\Controller\\FoldersController))",
                "#11 \/home\/bato\/ws\/github\/bedita\/bedita4\/vendor\/cakephp\/cakephp\/src\/Http\/BaseApplication.php(234): Cake\\Http\\ActionDispatcher-\u003Edispatch(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response))",
                "#12 \/home\/bato\/ws\/github\/bedita\/bedita4\/vendor\/cakephp\/cakephp\/src\/Http\/Runner.php(65): Cake\\Http\\BaseApplication-\u003E__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response), Object(Cake\\Http\\Runner))",
                "#13 \/home\/bato\/ws\/github\/bedita\/bedita4\/vendor\/cakephp\/cakephp\/src\/Routing\/Middleware\/RoutingMiddleware.php(162): Cake\\Http\\Runner-\u003E__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response))",
                "#14 \/home\/bato\/ws\/github\/bedita\/bedita4\/vendor\/cakephp\/cakephp\/src\/Http\/Runner.php(65): Cake\\Routing\\Middleware\\RoutingMiddleware-\u003E__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response), Object(Cake\\Http\\Runner))",
                "#15 \/home\/bato\/ws\/github\/bedita\/bedita4\/vendor\/cakephp\/cakephp\/src\/Routing\/Middleware\/AssetMiddleware.php(88): Cake\\Http\\Runner-\u003E__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response))",
                "#16 \/home\/bato\/ws\/github\/bedita\/bedita4\/vendor\/cakephp\/cakephp\/src\/Http\/Runner.php(65): Cake\\Routing\\Middleware\\AssetMiddleware-\u003E__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response), Object(Cake\\Http\\Runner))",
                "#17 \/home\/bato\/ws\/github\/bedita\/bedita4\/vendor\/cakephp\/cakephp\/src\/Error\/Middleware\/ErrorHandlerMiddleware.php(96): Cake\\Http\\Runner-\u003E__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response))",
                "#18 \/home\/bato\/ws\/github\/bedita\/bedita4\/vendor\/cakephp\/cakephp\/src\/Http\/Runner.php(65): Cake\\Error\\Middleware\\ErrorHandlerMiddleware-\u003E__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response), Object(Cake\\Http\\Runner))",
                "#19 \/home\/bato\/ws\/github\/bedita\/bedita4\/plugins\/BEdita\/API\/src\/Middleware\/CorsMiddleware.php(94): Cake\\Http\\Runner-\u003E__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response))",
                "#20 \/home\/bato\/ws\/github\/bedita\/bedita4\/vendor\/cakephp\/cakephp\/src\/Http\/Runner.php(65): BEdita\\API\\Middleware\\CorsMiddleware-\u003E__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response), Object(Cake\\Http\\Runner))",
                "#21 \/home\/bato\/ws\/github\/bedita\/bedita4\/plugins\/BEdita\/API\/src\/Middleware\/AnalyticsMiddleware.php(134): Cake\\Http\\Runner-\u003E__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response))",
                "#22 \/home\/bato\/ws\/github\/bedita\/bedita4\/vendor\/cakephp\/cakephp\/src\/Http\/Runner.php(65): BEdita\\API\\Middleware\\AnalyticsMiddleware-\u003E__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response), Object(Cake\\Http\\Runner))",
                "#23 \/home\/bato\/ws\/github\/bedita\/bedita4\/vendor\/cakephp\/cakephp\/src\/Http\/Runner.php(51): Cake\\Http\\Runner-\u003E__invoke(Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response))",
                "#24 \/home\/bato\/ws\/github\/bedita\/bedita4\/vendor\/cakephp\/cakephp\/src\/Http\/Server.php(97): Cake\\Http\\Runner-\u003Erun(Object(Cake\\Http\\MiddlewareQueue), Object(Cake\\Http\\ServerRequest), Object(Cake\\Http\\Response))",
                "#25 \/home\/bato\/ws\/github\/bedita\/bedita4\/webroot\/index.php(40): Cake\\Http\\Server-\u003Erun()",
                "#26 {main}"
            ]
        }
    },
    "links": {
        "self": "http:\/\/bedita4.localhost\/folders\/3\/relationships\/children",
        "home": "http:\/\/bedita4.localhost\/home"
    }
}
```
